#!/usr/bin/python3

import sys
import os
from typing import List, Tuple

SRC_FOLDER	=	"src"
EXTENSION	=	"c"

def	query_files_in_folder(root_folder: str) -> List[str]:
	sources: List[str] = []
	ROOT_FOLDER_LENGTH = len(root_folder)
	for path, _, files in os.walk(root_folder):
		path = path[ROOT_FOLDER_LENGTH:]
		if path.startswith('/'):
			path = path[1:]
		if path:
			path += '/'
		for file in files:
			if file.endswith('.' + EXTENSION):
				sources.append(path + file[:-len('.' + EXTENSION)])
	return (sources)

if __name__ == "__main__":
	could_open: bool = False
	for arg in sys.argv[1:]:
		if arg.startswith('--type=') or arg.startswith('-t='):
			EXTENSION = arg.split('=', 1)[1]
		elif arg.startswith('--root=') or arg.startswith('-r='):
			SRC_FOLDER = arg.split('=', 1)[1]
		else:
			print('Unknown augument:', arg, file=sys.stderr)
			exit(1)
	try:
		with open('Files.mk', 'w') as output_file:
			line: str = ''
			lines: List[str] = []
			could_open = True
			for source in query_files_in_folder(SRC_FOLDER):
				L: int = len(line)
				if L == 0:
					line = source
				elif L + len(source) + 1 > 71:
					N: int = (71 - L) // 4
					lines.append('\t' + line + ('\t' * N) + '\t\\')
					line = source
				else:
					line += ' ' + source
			if line != '':
				N: int = (71 - len(line)) // 4
				lines.append('\t' + line + ('\t' * N) + '\t\\')
			output_file.write('FILES\t=' + ('\t' * 17) + '\\\n')
			for line in lines:
				output_file.write(line + '\n')
	except IOError as error:
		print("IOError:", error, file=sys.stderr)
	exit(0 if could_open else 1)